### ISSUE TITLE
Updated from 2.3.3 to 2.4.0, everything has been reset

### ISSUE THREAD

**Issue by dferrandizmont** [koliva8245/HeroesMatchTracker#12]
As title says just updated from 2.3.3 to 2.4.0 (by downloading the new exe) and just reset database and profile (must introduce it again).

**Comment by koliva8245** [comment]
When you run the `HeroesMatchTrackerSetup.exe` it will delete everything in the folder before being installing.  So if your going to update you have to let it automatically update or make a backup of the `Database` folder.

As a side note, I have been working on moving the default location of the database out of its current location to prevent this from happening.

**Comment by dferrandizmont** [comment]
Haven't thought about this ... you're correct! I'll not do it again, thanks!
