### ISSUE TITLE
Unexpected Result on Replay

### ISSUE THREAD

**Issue by mikec83** [koliva8245/HeroesMatchTracker#13]
Replay attached, the HMM says unexpected result.

[Infernal Shrines (127).zip](https://github.com/koliva8245/HeroesMatchTracker/files/1321199/Infernal.Shrines.127.zip)

**Comment by koliva8245** [comment]
That's one of the ["weird replays"](https://github.com/barrett777/Heroes.ReplayParser/blob/master/Heroes.ReplayParser/MPQFiles/ReplayDetails.cs#L45) were it's missing some data.   Nothing I can do about it now.

**Comment by koliva8245** [comment]
Most of these types of replays will now be parsed. If there's anymore that you come across, please let me know.
