### ISSUE TITLE
Talent icons not displayed

### ISSUE THREAD

**Issue by wompo** [koliva8245/HeroesMatchTracker#17]
The talent icons are not displayed in the app when installed from the HeroesMatchTrackerSetup.exe. I am running Heroes Match Tracker 2.5.0 on Windows 7 64bit.

![image](https://user-images.githubusercontent.com/11043165/32509227-659c6bea-c3f5-11e7-961e-73de608c0f01.png)

![image](https://user-images.githubusercontent.com/11043165/32509353-b8f6ecde-c3f5-11e7-9a5c-640fe21eb756.png)

**Comment by koliva8245** [comment]
I noticed that the images that aren't appearing are the .dds images.  After some research it seems to be something with Windows 7, Windows Imaging Component (WIC), and possibly not supporting WDDM 1.2.

So I guess I'll have to convert the all .dds images now.

**Comment by koliva8245** [comment]
This should be fixed now
