### ISSUE TITLE
Ability to filter on friends and heroes

### ISSUE THREAD

**Issue by AndrewPalozzo** [koliva8245/HeroesMatchTracker#19]
Long shot here and not sure if this is the place to ask, but me and my friends have been trying various duo and triple combinations in QM. Is there any way I can filter this data so i can see when we both played hero x & y for example and see how it's performed?

**Comment by koliva8245** [comment]
Nope, afraid not.

**Comment by AndrewPalozzo** [comment]
Any chance of a feature request/enhancement? :)

**Comment by koliva8245** [comment]
I have some ideas for this, but it is a large enhancement and will take quite a while to do.  This will have wait until version 3.x.0

**Comment by koliva8245** [comment]
Didn't get this done in time for 2.7.0, but will be done for 2.8.0.

**Comment by AndrewPalozzo** [comment]
Oh wow! Didn't think you'd be able to turn it around that quick! Super excited can't wait!!

**Comment by AndrewPalozzo** [comment]
I love you! I can't wait to get home and test this out!
