### ISSUE TITLE
Unable to update from 2.6.0 to 2.6.4

### ISSUE THREAD

**Issue by wompo** [koliva8245/HeroesMatchTracker#20]
Log file:

[2017-12-29 12_10_20.6394.txt](https://github.com/koliva8245/HeroesMatchTracker/files/1592932/2017-12-29.12_10_20.6394.txt)

**Comment by koliva8245** [comment]
I have no idea why you're getting that error.  
You'll have to download and install v2.6.4.   Be sure to make a backup of your database folder before you install v2.6.4, otherwise it will be wiped.

Database is located at `C:\Users\<USER>\AppData\Local\HeroesMatchTracker\Databases`
