### ISSUE TITLE
Unable to set a profile

### ISSUE THREAD

**Issue by rayder13** [koliva8245/HeroesMatchTracker#24]
Currently unable to set a profile in the profile window. parsed almost 1400 replays and no battle tags show up in the drop down and get an error saying battle tag not found in database. closed application multiple times and made sure replay parses were up to current but still no luck.

**Comment by koliva8245** [comment]
Did you set the correct region before clicking on the Add Profile button?

**Comment by rayder13** [comment]
Yes. Even changed to each different region one by one to check and none of them worked.

**Comment by koliva8245** [comment]
Send me a replay file.

**Comment by rayder13** [comment]
battle tag is rayder#1534
[Battlefield of Eternity (74).zip](https://github.com/koliva8245/HeroesMatchTracker/files/2592365/Battlefield.of.Eternity.74.zip)

**Comment by koliva8245** [comment]
So it works fine. 

Enter your battletag in the battletag text field (it is case sensitive, having your name in all lowercase letter will cause it not to be found), leave on `US` for the region, click `Add Profile`.

Then in the `Selected BattleTag` dropdown, your battletag should appear.  Select it, and click on the `Set` button.

**Comment by rayder13** [comment]
Ok. Wasn't aware it was case sensitive. Maybe in the next update a note could be made on the profile menu about case sensitivity? Or at least in the wiki entry for setup. I appreciate the help :D
