### ISSUE TITLE
Application not starting

### ISSUE THREAD

**Issue by tcaruth** [koliva8245/HeroesMatchTracker#7]
There is no log folder in the app-2.1.0 folder. I have not used this app in the past, so there are no other installation folders.

I saw .NET 4.6.2 is required. .NET 4.7 was installed with the recent Windows update. When downloading KB3151800 to force installation of 4.6.2, I am told ".NET Framework 4.6.2 or a later update is already installed on this computer."

I downloaded the 2.0.1 and 2.0.0 releases as well, and nothing creates a log to show you, or starts the application. I can see 2 entries in my task manager for HeroesMatchTracker.exe, but one closes quickly, and the other after 5-10 seconds.

Please advise.

**Comment by tcaruth** [comment]
Opening the Event Viewer, I can see the following errors.
----------
> Log Name:      Application
> Source:        .NET Runtime
> Date:          5/18/2017 5:02:07 AM
> Event ID:      1026
> Task Category: None
> Level:         Error
> Keywords:      Classic
> User:          N/A
> Computer:      Travis-PC
> Description:
> Application: HeroesMatchTracker.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: exception code c0000005, exception address 00007FFEF4A0FD0C
----------
> Log Name:      Application
> Source:        Application Error
> Date:          5/18/2017 5:02:07 AM
> Event ID:      1000
> Task Category: (100)
> Level:         Error
> Keywords:      Classic
> User:          N/A
> Computer:      Travis-PC
> Description:
> Faulting application name: HeroesMatchTracker.exe, version: 2.1.0.0, time stamp: 0x591bad70
> Faulting module name: d3d9.dll, version: 10.0.15063.0, time stamp: 0x631de416
> Exception code: 0xc0000005
> Fault offset: 0x000000000000fd0c
> Faulting process id: 0x2a7c
> Faulting application start time: 0x01d2cfbdce333489
> Faulting application path: C:\Users\tcaru\AppData\Local\HeroesMatchTracker\app-2.1.0\HeroesMatchTracker.exe
> Faulting module path: C:\WINDOWS\SYSTEM32\d3d9.dll
> Report Id: 95495aef-4984-4cc0-b0ad-3907ef44c0ac
> Faulting package full name: 
> Faulting package-relative application ID:

**Comment by koliva8245** [comment]
Delete the application and download and run Heroes Match Tracker 2.0.2.
Lets see if that works.

**Comment by koliva8245** [comment]
Oh wait nevermind. You tried it already.

**Comment by koliva8245** [comment]
Try running it in administer mode?

**Comment by koliva8245** [comment]
Since it seems to be an error with d3d9.dll I guess try (force) installing directx 9.0c. https://www.microsoft.com/en-us/download/details.aspx?id=34429.

But I don't think this will work either.

**Comment by koliva8245** [comment]
Looks like I broke the email notifications.  Best to check out replies on
GitHub.

**Comment by tcaruth** [comment]
i can't install that runtime because
> Windows 2000, Windows 2000 Advanced Server, Windows 2000 Professional Edition , Windows 2000 Server, Windows 2000 Service Pack 2, Windows 2000 Service Pack 3, Windows 2000 Service Pack 4, Windows 98, Windows 98 Second Edition, Windows ME, Windows Server 2003, Windows XP, Windows XP Home Edition , Windows XP Media Center Edition, Windows XP Professional Edition, Windows XP Service Pack 1

i do have d3d9.dll installed on my computer, searching finds it in a subfolder of the windows folder. i believe it comes attached to windows 10, as well as nearly every steam game.

**Comment by tcaruth** [comment]
i tried a few things, namely trying the proper install of [DirectX End-User Runtime Web Installer](https://www.microsoft.com/en-ca/download/details.aspx?id=35)
and then on a whim, the [Visual C++ Redistributable for Visual Studio 2012 Update 4](https://www.microsoft.com/en-us/download/details.aspx?id=30679)

one of those partially fixed my issue, and now i get an error log
[_StartupLog.txt](https://github.com/koliva8245/HeroesMatchTracker/files/1013327/_StartupLog.txt)

**Comment by tcaruth** [comment]
reading that log, it says the directory isnt found, so I made a Logs folder. I'm guessing when I tried to install an older version, I was flagged for possibly needing a database migration, so it was expected that folder should already be there. 
[DatabasesMigrationLog.txt](https://github.com/koliva8245/HeroesMatchTracker/files/1013335/DatabasesMigrationLog.txt)

rerunning the exe, it got further this time, creating an UpdateLog.txt and another [_StartupLog.txt](https://github.com/koliva8245/HeroesMatchTracker/files/1013338/_StartupLog.txt). this is usually where i'd give up, so i deleted the folder from appdata and reinstalled one more time. the application now starts, with no errors and 3 logs in the app-2.1.0/Logs/ folder. i've messed around briefly, and everything seems to work how i'd imagine it should.

i'll let you close the issue, so i know you've seen it. if future people have issues, i think the visual c++ reinstall was what got my issue moving, so maybe start there.

**Comment by koliva8245** [comment]
Interesting, the only thing that uses C++ is the squirrel updater.

Those errors you were getting, like the Logs folder error, are caused by
running the HeroesMatchTracker.exe directly. You need to run the app from
the shortcut.

I know there's two exe files.  One in %LocalAppData%\HeroesMatchTracker\
and in %LocalAppData%\HeroesMatchTracker\app-<Version>\.  I can't test it
now, but I think of one them causes the issue, or maybe both do.

**Comment by koliva8245** [comment]
The one in `%LocalAppData%\HeroesMatchTracker\` causes the path issue, unless you use a shortcut link to it.
