### ISSUE TITLE
Seeing TranslationException with hotslogs uploads

### ISSUE THREAD

**Issue by mikec83** [koliva8245/HeroesMatchTracker#9]
Version: 2.20

Replays are showing TranslationException failure for auto upload.  If I requeue them, they work.

**Comment by koliva8245** [comment]
I need to see the log file, TranslationReplays.txt. 
https://github.com/koliva8245/HeroesMatchTracker/wiki/Non-English-Clients

**Comment by mikec83** [comment]
It was an english replay.  File attached.[](url)
[Dragon Shire (17).zip](https://github.com/koliva8245/HeroesMatchTracker/files/1079573/Dragon.Shire.17.zip)

**Comment by koliva8245** [comment]
I'm puzzled.

Just to be clear, it showed TranslationException in the `Status` column right?  If it did, then it had to produce a TranslationReplays.txt file or some sort of log file.

**Comment by mikec83** [comment]
Where would that txt file be located?

**Comment by koliva8245** [comment]
`%LocalAppData%\HeroesMatchTracker\app-<2.x.x>\Logs`

**Comment by mikec83** [comment]
Yep i found it and edited my comment with the translation file.  It seems it doesn't know how to handle "Malthael" so any game with Malthael in it gets the error.

**Comment by koliva8245** [comment]
That's weird.

Take a look in \Xml\Heroes\Heroes.xml and search for Malthael.
Also in \Xml\HeroBuilds\ there should be a 54339 folder and in it a
Malthael.xml file.

**Comment by koliva8245** [comment]
Is this still an issue?

**Comment by m0uSe84** [comment]
Seems so, got the same problem:
http://i.imgur.com/MrHMMni.png

**Comment by koliva8245** [comment]
[hmt_data.zip](https://github.com/koliva8245/HeroesMatchTracker/files/1103748/hmt_data.zip)
Download and unzip. Close HMT and copy and replace this file in `\app-2.2.1\lib\`

Then try parsing again and when you get `TranslationException` again, then show me the `TranslationReplays.txt` log file.

**Comment by m0uSe84** [comment]
Better, but this ends with:
http://i.imgur.com/IzDyojV.png

**Comment by koliva8245** [comment]
That I added file doesn't help with the parsing, it was just for extra logging, that's why I wanted to see the `TranslationReplays.txt` log file.

But anyways your screenshot does seem to indicate that a file might be missing.
Take a look in `\Xml\Heroes\Heroes.xml` and search for Malthael. Also in `\Xml\HeroBuilds\` there should be a 54339 folder and in it a `Malthael.xml` file.

**Comment by m0uSe84** [comment]
Both are there.

**Comment by koliva8245** [comment]
In the application, in `About` what version does it say for `Heroes.Icons` (including the number in parentheses)?

**Comment by m0uSe84** [comment]
http://i.imgur.com/zoBomfM.png

**Comment by koliva8245** [comment]
Yeah, right version (2.2.1) wrong build (53548). It should be 54339, which means it didn't find the 54339 folder. You sure it's there? http://i.imgur.com/uhjxtlZ.png

**Comment by m0uSe84** [comment]
It is:
http://imgur.com/a/CxywO

**Comment by koliva8245** [comment]
I really don't know what's going on. I'm going to have to add some file
verification/more bugging for version 2.3.0.

However try the following as a workaround.
1. Create a new build folder and name it a higher number than 54339, so
like 54400
2. In that folder create a file called _AllHeroes.xml
3. In that xml file paste the following
<?xml version="1.0" encoding="utf-8" ?>
<Heroes pre="54339" />

You can also just copy the _AllHeroes.xml file from the 53174 folder, but
then changed the pre="52986" number to 54339.

Be sure to restart the application and then check the About menu again to
see what build it has for Heroes.Icons.

**Comment by koliva8245** [comment]
If you're still having this issue with 2.3.0, please create a new issue.
